name: local_sync
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^5.8.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.0.3
  bonsoir: ^6.0.1
  device_info_plus: ^12.2.0
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
