// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/identity.dart';
import 'api/trust.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1993103111;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_local_sync',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<NetworkIdentity> crateApiIdentityNetworkIdentityFromMnemonic({
    required String phrase,
    required String salt,
  });

  Future<Uint8List> crateApiIdentityNetworkIdentityGetClusterProof({
    required NetworkIdentity that,
  });

  Future<String> crateApiIdentityNetworkIdentityPublicId({
    required NetworkIdentity that,
  });

  Future<bool> crateApiIdentityNetworkIdentityVerifyClusterMembership({
    required NetworkIdentity that,
    required String peerNodeIdHex,
    required List<int> proof,
  });

  Future<void> crateApiVaultDecryptFileStream({
    required String inputPath,
    required String outputPath,
    required List<int> nonceBytes,
    required List<int> keyBytes,
  });

  Future<Uint8List> crateApiVaultDeriveVaultKey({required String mnemonic});

  Future<EncryptionResult> crateApiVaultEncryptFileStream({
    required String inputPath,
    required String outputPath,
    required List<int> keyBytes,
  });

  Future<TlsConfig> crateApiTrustGenerateEphemeralCert();

  Future<String> crateApiIdentityGenerateMnemonicWords();

  Future<Uint8List> crateApiTrustSignChallenge({
    required NetworkIdentity identity,
    required List<int> challenge,
  });

  Future<bool> crateApiIdentityValidateMnemonicWords({required String phrase});

  Future<bool> crateApiTrustVerifyResponse({
    required String publicKeyHex,
    required List<int> challenge,
    required List<int> signatureBytes,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NetworkIdentity;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NetworkIdentity;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NetworkIdentityPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<NetworkIdentity> crateApiIdentityNetworkIdentityFromMnemonic({
    required String phrase,
    required String salt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          sse_encode_String(salt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIdentityNetworkIdentityFromMnemonicConstMeta,
        argValues: [phrase, salt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityNetworkIdentityFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkIdentity_from_mnemonic",
        argNames: ["phrase", "salt"],
      );

  @override
  Future<Uint8List> crateApiIdentityNetworkIdentityGetClusterProof({
    required NetworkIdentity that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityNetworkIdentityGetClusterProofConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityNetworkIdentityGetClusterProofConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkIdentity_get_cluster_proof",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiIdentityNetworkIdentityPublicId({
    required NetworkIdentity that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityNetworkIdentityPublicIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityNetworkIdentityPublicIdConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkIdentity_public_id",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiIdentityNetworkIdentityVerifyClusterMembership({
    required NetworkIdentity that,
    required String peerNodeIdHex,
    required List<int> proof,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
            that,
            serializer,
          );
          sse_encode_String(peerNodeIdHex, serializer);
          sse_encode_list_prim_u_8_loose(proof, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIdentityNetworkIdentityVerifyClusterMembershipConstMeta,
        argValues: [that, peerNodeIdHex, proof],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIdentityNetworkIdentityVerifyClusterMembershipConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkIdentity_verify_cluster_membership",
        argNames: ["that", "peerNodeIdHex", "proof"],
      );

  @override
  Future<void> crateApiVaultDecryptFileStream({
    required String inputPath,
    required String outputPath,
    required List<int> nonceBytes,
    required List<int> keyBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_list_prim_u_8_loose(nonceBytes, serializer);
          sse_encode_list_prim_u_8_loose(keyBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultDecryptFileStreamConstMeta,
        argValues: [inputPath, outputPath, nonceBytes, keyBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultDecryptFileStreamConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_file_stream",
        argNames: ["inputPath", "outputPath", "nonceBytes", "keyBytes"],
      );

  @override
  Future<Uint8List> crateApiVaultDeriveVaultKey({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultDeriveVaultKeyConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultDeriveVaultKeyConstMeta =>
      const TaskConstMeta(
        debugName: "derive_vault_key",
        argNames: ["mnemonic"],
      );

  @override
  Future<EncryptionResult> crateApiVaultEncryptFileStream({
    required String inputPath,
    required String outputPath,
    required List<int> keyBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_list_prim_u_8_loose(keyBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encryption_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultEncryptFileStreamConstMeta,
        argValues: [inputPath, outputPath, keyBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultEncryptFileStreamConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_file_stream",
        argNames: ["inputPath", "outputPath", "keyBytes"],
      );

  @override
  Future<TlsConfig> crateApiTrustGenerateEphemeralCert() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tls_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTrustGenerateEphemeralCertConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTrustGenerateEphemeralCertConstMeta =>
      const TaskConstMeta(debugName: "generate_ephemeral_cert", argNames: []);

  @override
  Future<String> crateApiIdentityGenerateMnemonicWords() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGenerateMnemonicWordsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateMnemonicWordsConstMeta =>
      const TaskConstMeta(debugName: "generate_mnemonic_words", argNames: []);

  @override
  Future<Uint8List> crateApiTrustSignChallenge({
    required NetworkIdentity identity,
    required List<int> challenge,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
            identity,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(challenge, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTrustSignChallengeConstMeta,
        argValues: [identity, challenge],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTrustSignChallengeConstMeta => const TaskConstMeta(
    debugName: "sign_challenge",
    argNames: ["identity", "challenge"],
  );

  @override
  Future<bool> crateApiIdentityValidateMnemonicWords({required String phrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityValidateMnemonicWordsConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityValidateMnemonicWordsConstMeta =>
      const TaskConstMeta(
        debugName: "validate_mnemonic_words",
        argNames: ["phrase"],
      );

  @override
  Future<bool> crateApiTrustVerifyResponse({
    required String publicKeyHex,
    required List<int> challenge,
    required List<int> signatureBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKeyHex, serializer);
          sse_encode_list_prim_u_8_loose(challenge, serializer);
          sse_encode_list_prim_u_8_loose(signatureBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTrustVerifyResponseConstMeta,
        argValues: [publicKeyHex, challenge, signatureBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTrustVerifyResponseConstMeta =>
      const TaskConstMeta(
        debugName: "verify_response",
        argNames: ["publicKeyHex", "challenge", "signatureBytes"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NetworkIdentity => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NetworkIdentity => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  NetworkIdentity
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkIdentityImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NetworkIdentity
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkIdentityImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NetworkIdentity
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkIdentityImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EncryptionResult dco_decode_encryption_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return EncryptionResult(nonce: dco_decode_list_prim_u_8_strict(arr[0]));
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  TlsConfig dco_decode_tls_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TlsConfig(
      keyPem: dco_decode_String(arr[0]),
      certPem: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  NetworkIdentity
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkIdentityImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NetworkIdentity
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkIdentityImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NetworkIdentity
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkIdentityImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EncryptionResult sse_decode_encryption_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nonce = sse_decode_list_prim_u_8_strict(deserializer);
    return EncryptionResult(nonce: var_nonce);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  TlsConfig sse_decode_tls_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyPem = sse_decode_String(deserializer);
    var var_certPem = sse_decode_String(deserializer);
    return TlsConfig(keyPem: var_keyPem, certPem: var_certPem);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    NetworkIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkIdentityImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    NetworkIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkIdentityImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkIdentity(
    NetworkIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkIdentityImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_encryption_result(
    EncryptionResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.nonce, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_tls_config(TlsConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.keyPem, serializer);
    sse_encode_String(self.certPem, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class NetworkIdentityImpl extends RustOpaque implements NetworkIdentity {
  // Not to be used by end users
  NetworkIdentityImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NetworkIdentityImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NetworkIdentity,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NetworkIdentity,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NetworkIdentityPtr,
  );

  /// Returns the proof that this Node belongs to the Cluster.
  Future<Uint8List> getClusterProof() => RustLib.instance.api
      .crateApiIdentityNetworkIdentityGetClusterProof(that: this);

  Future<String> publicId() =>
      RustLib.instance.api.crateApiIdentityNetworkIdentityPublicId(that: this);

  /// Verifies that a peer's Node ID was signed by OUR Cluster Key.
  Future<bool> verifyClusterMembership({
    required String peerNodeIdHex,
    required List<int> proof,
  }) => RustLib.instance.api
      .crateApiIdentityNetworkIdentityVerifyClusterMembership(
        that: this,
        peerNodeIdHex: peerNodeIdHex,
        proof: proof,
      );
}
