import 'dart:io'; // For Platform info
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:local_sync/features/identity/domain/device_identity.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:local_sync/src/rust/api/identity.dart'
    as rust_api; // Generated by FRB

/// Handles the cryptographic identity using the Rust FFI layer.
class IdentityService {
  final FlutterSecureStorage _secureStorage;
  final SharedPreferences _prefs;

  static const _privateKeyStorageKey = 'device_private_key_pem';
  static const _publicCertStorageKey = 'device_public_cert_pem';
  static const _deviceIdKey = 'device_id_fingerprint';
  static const _deviceNameKey = 'device_display_name';

  IdentityService(this._secureStorage, this._prefs);

  /// Gets the existing identity or generates a new one via Rust.
  Future<DeviceIdentity> getOrCreateIdentity() async {
    // 1. Try to load existing credentials
    final privateKeyPem = await _secureStorage.read(key: _privateKeyStorageKey);
    final publicCertPem = _prefs.getString(_publicCertStorageKey);
    final deviceId = _prefs.getString(_deviceIdKey);
    final deviceName = _prefs.getString(_deviceNameKey);

    if (privateKeyPem != null &&
        publicCertPem != null &&
        deviceId != null &&
        deviceName != null) {
      return DeviceIdentity(
        deviceId: deviceId,
        deviceName: deviceName,
        privateKeyPem: privateKeyPem,
        publicCertPem: publicCertPem,
      );
    }

    // 2. Fallback: Create new identity
    return _createNewIdentity();
  }

  Future<DeviceIdentity> _createNewIdentity() async {
    // Clear potentially partial old data
    await _secureStorage.delete(key: _privateKeyStorageKey);
    await _prefs.remove(_publicCertStorageKey);

    // 1. Determine Display Name (e.g., "Pixel 6", "Abhishek's MacBook")
    String displayName = "LocalSync Device";
    try {
      if (Platform.isAndroid || Platform.isIOS) {
        // In a real app, use device_info_plus to get actual model name
        displayName = Platform.isAndroid ? "Android Device" : "iOS Device";
      } else {
        displayName = Platform.localHostname;
      }
    } catch (e) {
      // Fallback if platform lookup fails
    }

    // 2. Call Rust FFI (Runs on thread pool, safe to await)
    // logic: generate_identity(display_name)
    final rustIdentity = await rust_api.generateIdentity(
      displayName: displayName,
    );

    // 3. Persist Securely
    await _secureStorage.write(
      key: _privateKeyStorageKey,
      value: rustIdentity.privateKeyPem,
    );
    await _prefs.setString(_publicCertStorageKey, rustIdentity.certificatePem);
    await _prefs.setString(_deviceIdKey, rustIdentity.deviceId);
    await _prefs.setString(_deviceNameKey, rustIdentity.deviceName);

    // 4. Return Domain Object
    return DeviceIdentity(
      deviceId: rustIdentity.deviceId,
      deviceName: rustIdentity.deviceName,
      privateKeyPem: rustIdentity.privateKeyPem,
      publicCertPem: rustIdentity.certificatePem,
    );
  }
}
