// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a new 24-word BIP39 mnemonic.
Future<String> generateMnemonicWords() =>
    RustLib.instance.api.crateApiIdentityGenerateMnemonicWords();

/// Validates if a string is a valid BIP39 mnemonic.
Future<bool> validateMnemonicWords({required String phrase}) =>
    RustLib.instance.api.crateApiIdentityValidateMnemonicWords(phrase: phrase);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetworkIdentity>>
abstract class NetworkIdentity implements RustOpaqueInterface {
  static Future<NetworkIdentity> fromMnemonic({
    required String phrase,
    required String salt,
  }) => RustLib.instance.api.crateApiIdentityNetworkIdentityFromMnemonic(
    phrase: phrase,
    salt: salt,
  );

  /// Returns the proof that this Node belongs to the Cluster.
  Future<Uint8List> getClusterProof();

  Future<String> publicId();

  /// Verifies that a peer's Node ID was signed by OUR Cluster Key.
  Future<bool> verifyClusterMembership({
    required String peerNodeIdHex,
    required List<int> proof,
  });
}
