// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<LocalIdentity> generateIdentitySimple({required String mnemonic}) =>
    RustLib.instance.api.crateApiIdentityGenerateIdentitySimple(
      mnemonic: mnemonic,
    );

class LocalIdentity {
  final String deviceId;

  const LocalIdentity({required this.deviceId});

  @override
  int get hashCode => deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalIdentity &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId;
}
