// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'identity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a self-signed X.509 certificate for the TLS handshake.
Future<TlsConfig> generateEphemeralCert() =>
    RustLib.instance.api.crateApiTrustGenerateEphemeralCert();

/// Signs a challenge using the identity's private key.
Future<Uint8List> signChallenge({
  required NetworkIdentity identity,
  required List<int> challenge,
}) => RustLib.instance.api.crateApiTrustSignChallenge(
  identity: identity,
  challenge: challenge,
);

/// Verifies that a response matches a known public key.
Future<bool> verifyResponse({
  required String publicKeyHex,
  required List<int> challenge,
  required List<int> signatureBytes,
}) => RustLib.instance.api.crateApiTrustVerifyResponse(
  publicKeyHex: publicKeyHex,
  challenge: challenge,
  signatureBytes: signatureBytes,
);

class TlsConfig {
  final String keyPem;
  final String certPem;

  const TlsConfig({required this.keyPem, required this.certPem});

  @override
  int get hashCode => keyPem.hashCode ^ certPem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TlsConfig &&
          runtimeType == other.runtimeType &&
          keyPem == other.keyPem &&
          certPem == other.certPem;
}
