// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'vault.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SecureKey`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `zeroize`

Future<EncryptionResult> encryptFileStream({
  required String inputPath,
  required String outputPath,
  required List<int> keyBytes,
}) => RustLib.instance.api.crateApiVaultEncryptFileStream(
  inputPath: inputPath,
  outputPath: outputPath,
  keyBytes: keyBytes,
);

Future<void> decryptFileStream({
  required String inputPath,
  required String outputPath,
  required List<int> nonceBytes,
  required List<int> keyBytes,
}) => RustLib.instance.api.crateApiVaultDecryptFileStream(
  inputPath: inputPath,
  outputPath: outputPath,
  nonceBytes: nonceBytes,
  keyBytes: keyBytes,
);

Future<Uint8List> deriveVaultKey({required String mnemonic}) =>
    RustLib.instance.api.crateApiVaultDeriveVaultKey(mnemonic: mnemonic);

@freezed
sealed class EncryptionResult with _$EncryptionResult {
  const factory EncryptionResult({required Uint8List nonce}) =
      _EncryptionResult;
}
