import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart'; // For debugPrint
import 'package:local_sync/features/vault/data/vault_repository.dart';
import 'package:path/path.dart' as p;
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:uuid/uuid.dart';

part 'vault_handler.g.dart';

class VaultHandler {
  final VaultRepository _repository;
  final void Function() _onFileHandled;
  final Directory _vaultDir;

  VaultHandler(this._repository, this._onFileHandled, this._vaultDir);

  /// Called when MessageRouter has finished downloading a file to temp.
  ///
  /// The [fileId] is generated by the sender and serves as the unique handle
  /// for this file transaction.
  Future<void> handleCompletedFile({
    required String fileId,
    required String tempFilePath,
    required String filename,
    required String nonceBase64,
  }) async {
    try {
      final tempFile = File(tempFilePath);
      final finalPath = p.join(_vaultDir.path, fileId);

      // 1. Move temp file to final vault location (Atomic rename usually)
      if (await tempFile.exists()) {
        await tempFile.rename(finalPath);
      } else {
        throw Exception("Temp file not found at $tempFilePath");
      }

      // 2. Save Metadata to Repository
      await _repository.addFile(
        id: fileId,
        filename: filename,
        nonce: base64Decode(nonceBase64),
        ciphertextPath: finalPath,
      );

      // 3. Notify UI
      _onFileHandled();
      debugPrint('Vault file finalized: $filename');
    } catch (e) {
      debugPrint('Error finalizing vault file: $e');
      // Cleanup temp if it exists (in case rename failed)
      try {
        final f = File(tempFilePath);
        if (await f.exists()) await f.delete();
      } catch (_) {}
    }
  }
}

@riverpod
Uuid uuid(Ref ref) => const Uuid();

@riverpod
Future<VaultHandler> vaultHandler(Ref ref) async {
  final repository = await ref.watch(vaultRepositoryProvider.future);

  // Need the directory to save incoming files
  final appDocsDir = await ref.watch(appDocumentsDirectoryProvider.future);
  final vaultDir = Directory(p.join(appDocsDir.path, 'SecureVaultData'));
  if (!vaultDir.existsSync()) {
    vaultDir.createSync(recursive: true);
  }

  return VaultHandler(repository, () {
    // Refresh the list of vault files when a new one arrives
    ref.invalidate(vaultFilesProvider);
  }, vaultDir);
}
